### ISSUE TITLE
`createApiLoader` can not handle chunked data response

### ISSUE THREAD

**Issue by fiveid** [ekino/rendr#5]
Requests for large page data via `createApiLoader` never resolve. Only the first data chunk is ever processed by the Writable stream. 

This seems to affect data responses with a `content-length` somewhere in the region of 65000 bytes or more. 

## More information

I've isolated this issue to the `pipePageToClient` function in the file: `packages/loader/src/services/api.ts`.

A new Writable stream is created to build the data from chunks via the `.write` method:
```ts
let data = "";
  const dest = new Writable({
    write(chunk) {
      data += chunk;
    }
  });
```
However, `.write` is never called more than once. For streams coming in multiple chunks, the whole of the data is not collated and the request does not complete. 

The issue can be resolved by moving the functionality of `.write` into a callback triggered by the "data" event of the Readable stream, e.g.:

```ts
let data = "";
source.on("data", (chunk) => {
  data += chunk;
});
```

## Steps to reproduce

The issue can be reproduced in the test suite `packages/loader/src/services/api.test.ts`, in the `"test rendr/document mode, ie a Page"` test, by passing a large Page object to the `strPage` variable:

```ts
const strPage = JSON.stringify(createPage(MOCK_DATA));
```
I've attached some suitable JSON to use as `MOCK_DATA`: [ekino-rendr-loader-mock-page-object.json.zip](https://github.com/ekino/rendr/files/3555502/ekino-rendr-loader-mock-page-object.json.zip).

The test will timeout without passing. Increase the Jest timeout setting to 30,000 (`jest.setTimeout(30000)`) and the test will still fail to complete.

**Comment by rande** [comment]
Fixed by https://github.com/ekino/rendr/commit/b6ceb0ed834fd5a0d253699328772faa6e33345e
