### ISSUE TITLE
Add support for Drupal

### ISSUE THREAD

**Issue by rande** [ekino/rendr#7]
Add a drupal module to expose a rendr like compatible page.

# Requirements

 - The Drupal integration should support virtual site management (or channel); (ie not using the multi-site integration feature from Drupal).
 - Each page is a set of properties and blocks, main properties are: statusCode, template, cache information, etc ... see an example here: https://nextjs-with-remoteapi.rande.now.sh/api/

# Main tasks

- [x] create a drupal module: ekino_rendr for drupal
- [x] add dependencies to required external modules
- [ ] add any required content types
- [ ] add a default set of fixtures so external users can start with a real use case
- [ ] add a post content type (or module) to show how work the split between the structure and the content
- [ ] try to create a set of helper to improve the DX (ex: create a helper to define a block with mandatory fields: container, settings, order, type)
- [ ] expose the Page API and document how to get the filter per website/channel. So we can create a javascript example with a dedicated loader. 

# Notes

- For now, we use a mono-repo, so the PHP code need to go in the packages folders. This will likely not work with composer, so I plan to use https://github.com/splitsh/lite to make sure we can have a dedicated read-only repository.

**Comment by fancyweb** [comment]
Done:
- [x] Created the CRUD for the ChannelType entity
- [x] Created the CRUD for the Channel entity
- [x] Created the Template entity (no CRUD yet, import via Drupal config)
- [x] Created the CRUD for the Document entity
- [x] Added the dependency to paragraphs
- [x] Added the default raw html paragraph type

TODO for the MVP:
- [] Hook paragraphs in the Document entity
- [] Create the entities normalizers
- [] Create the API endpoint

**Comment by rande** [comment]
Automatic push to git.drupal.org is now in place.

https://github.com/ekino/rendr/runs/426541220

**Comment by srascar** [comment]
In `packages/cms-drupal/ekino_rendr.services.yml`, can you mention that the `priority: 9`
is important since it is a work around for a known issue.

```yaml
# Drupal core/modules/serialization/serialization.services.yml

      # Set the priority lower than the hal entity reference field item
      # normalizer, so that we do not replace that for hal_json but higher than
      # this modules generic field item normalizer.
      # @todo Find a better way for this in https://www.drupal.org/node/2575761.
```

**Comment by srascar** [comment]
This issue was too big and should actually be a milestone.
I will close it and move its description in the parent milestone.
